I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 74, in script call
    call fight_start(girl,rat)
  File "game/battle.rpy", line 32, in script call
    call fight_loop(player, enemy)
  File "game/battle.rpy", line 52, in script call
    call fight_loop(player,enemy)
  File "game/battle.rpy", line 52, in script call
    call fight_loop(player,enemy)
  File "game/battle.rpy", line 52, in script call
    call fight_loop(player,enemy)
  [Previous line repeated 20 more times]
  File "game/battle.rpy", line 51, in script
    jump wone_fight
ScriptError: could not find label 'wone_fight'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 74, in script call
    call fight_start(girl,rat)
  File "game/battle.rpy", line 32, in script call
    call fight_loop(player, enemy)
  File "game/battle.rpy", line 52, in script call
    call fight_loop(player,enemy)
  File "game/battle.rpy", line 52, in script call
    call fight_loop(player,enemy)
  File "game/battle.rpy", line 52, in script call
    call fight_loop(player,enemy)
  [Previous line repeated 20 more times]
  File "game/battle.rpy", line 51, in script
    jump wone_fight
  File "C:\2022portable_programs\renpy-8.2.3-sdk\renpy\ast.py", line 1701, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\2022portable_programs\renpy-8.2.3-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'wone_fight'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
SpringQuinox 1.0
Sat Sep  7 07:57:20 2024
